import fs from 'node:fs';
import assert from 'node:assert/strict';
const background = fs.readFileSync(new URL('../extension/background.js', import.meta.url), 'utf8');
const home = fs.readFileSync(new URL('../extension/home.js', import.meta.url), 'utf8');
const sidepanel = fs.readFileSync(new URL('../extension/sidepanel.js', import.meta.url), 'utf8');
assert.ok(background.includes("const RECOVERY_STATUSES = Object.freeze(['blocked-approval','paused']);"));
assert.ok(background.includes('Stall/runway observation is deliberately side-effect free'));
assert.ok(!background.includes("chrome.windows.create({ url: item.url"), 'Approval Recovery must not create a ChatGPT window');
assert.ok(!background.includes("chrome.tabs.update(state.tabId, { url: item.url"), 'Approval Recovery must not navigate saved ChatGPT URLs');
assert.ok(!background.includes("chrome.tabs.create({ url:requestedUrl"), 'Pulse must not recreate a missing ChatGPT target');
const watch = background.match(/async function watchForStalls\(\)[\s\S]*?\n}\n\nasync function ingestBatch/)?.[0] || '';
assert.ok(watch && !watch.includes('startApprovalRecovery('), 'stall watchdog must be observation-only');
assert.ok(background.includes("stopLegacyApprovalNavigation('v0.14.8 disabled legacy hidden ChatGPT navigation.')"));
assert.ok(background.includes("openByIdentity.has(identity)"), 'recovery queue must be bounded to open ChatGPT tabs');
assert.ok(!home.includes('hidden recovery window'));
const homeEnableLine = home.split('\n').find((line) => line.includes("$('approvalAutopilotEnabled').addEventListener")) || '';
const sideEnableLine = sidepanel.split('\n').find((line) => line.includes("$('panelApprovalEnabled').addEventListener")) || '';
assert.ok(homeEnableLine && !homeEnableLine.includes('PC_APPROVAL_RECOVERY_START'), 'enabling Home Autopilot must not start a sweep');
assert.ok(sideEnableLine && !sideEnableLine.includes('PC_APPROVAL_RECOVERY_START'), 'enabling Sidepanel Autopilot must not start a sweep');
console.log('navigation-safety: ok');
