import assert from 'node:assert/strict';
import {performance} from 'node:perf_hooks';
await import('../extension/src/project-router-core.js');
await import('../extension/src/project-memory-core.js');
const router=globalThis.ProjectConstellationProjectRouterCore;
const memory=globalThis.ProjectConstellationProjectMemoryCore;
const now=2_000_000_000_000;
const PROJECTS=500, CHATS=10000;
const projects=Array.from({length:PROJECTS},(_,i)=>({id:`p${i}`,sourceType:'workspace',name:`Constellation Domain ${i}`,description:`specialized domain${i} workflows artifacts testing release coordination`,updatedAt:now-i}));
const chats=Array.from({length:CHATS},(_,i)=>({id:`c${i}`,workspaceProjectId:i%9===0?'':`p${i%PROJECTS}`,workspaceProjectName:i%9===0?'':`Constellation Domain ${i%PROJECTS}`,title:`Domain${i%PROJECTS} implementation batch ${i}`,tags:[`domain${i%PROJECTS}`,'implementation'],lastUserExcerpt:`Continue domain${i%PROJECTS} artifact testing and release workflow`,lastExcerpt:`Validation for domain${i%PROJECTS} project`,status:i%31===0?'running':i%47===0?'stalled':'idle',updatedAt:now-i}));
let t0=performance.now();
const suggestions=router.suggestions({projects,chats,limit:80});
const routeMs=performance.now()-t0;
assert.ok(suggestions.length>0);
assert.ok(suggestions.length<=80,'router output is hard bounded');
assert.ok(routeMs<5000,`10k-chat/500-project router pass should stay bounded (${routeMs.toFixed(1)}ms)`);
const projectChats=chats.filter((c)=>c.workspaceProjectId==='p1').concat(Array.from({length:40},(_,i)=>({id:`live${i}`,title:`Domain1 concurrent implementation ${i}`,lastExcerpt:'domain1 shared renderer validation task',status:i<18?'running':'idle',updatedAt:now-i})));
const items=Array.from({length:5000},(_,i)=>({id:`k${i}`,kind:i%7===0?'decision':i%5===0?'follow-up':'recommendation',title:`Domain1 knowledge ${i}`,text:`Domain1 knowledge ${i} source-backed decision action`,chatId:projectChats[i%projectChats.length].id,confidence:.8,updatedAt:now-i,canonicalKey:`kind:${i}`}));
const files=Array.from({length:1500},(_,i)=>({id:`f${i}`,name:`artifact-${i}.zip`,updatedAt:now-i}));
t0=performance.now();
const compiled=memory.compileProjectBrain({project:projects[1],chats:projectChats,items,files,now});
const brainMs=performance.now()-t0;
assert.equal(compiled.workingSet.length<=12,true);
assert.equal(compiled.activeChats.length<=16,true);
assert.equal(compiled.coordination.pairs.length<=12,true);
assert.ok(brainMs<2500,`large Project Brain compile should stay bounded (${brainMs.toFixed(1)}ms)`);
console.log(JSON.stringify({projects:PROJECTS,chats:CHATS,routerMs:Number(routeMs.toFixed(1)),brainChats:projectChats.length,knowledge:items.length,files:files.length,brainMs:Number(brainMs.toFixed(1)),suggestions:suggestions.length,coordinationPairs:compiled.coordination.pairs.length}));
console.log('project-scale.test.mjs: PASS');
