from playwright.sync_api import sync_playwright
import json, pathlib, os
root = pathlib.Path(os.environ.get('PROJECT_CONSTELLATION_ROOT', '/mnt/data/project-constellation'))
fixture=(root.parent/'benchmarks/fixture.html').read_text(); core=(root/'src/core.js').read_text(); brain=(root/'src/brain-core.js').read_text(); health=(root/'src/health-core.js').read_text(); content=(root/'src/content.js').read_text(); css=(root/'src/styles.css').read_text()
mock=r'''(() => { const listeners=[]; window.__brain=[]; window.__messageCalls=0; window.ProjectConstellationProviders={detectProvider:()=>({id:'chatgpt',name:'ChatGPT',home:'https://chatgpt.com/'}),chatIdFromUrl:(u)=>{const m=String(u||'').match(/\/c\/([^/?#]+)/);return m?`chatgpt:${m[1]}`:'chatgpt:test';},isLikelyChatUrl:(u)=>/\/c\/[^/?#]+/.test(String(u||'')),canonicalChatUrl:(u)=>u,classifyExternalUrl:()=>({kind:'external',provider:'example.com',external:true}),hashString:(value)=>{let h=2166136261;for(const ch of String(value||'')){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return (h>>>0).toString(36);}}; window.chrome={storage:{local:{get:async()=>({projectConstellationPerformanceSettings:{enabled:true,responsiveScrolling:true,adaptiveMotionRelief:false},projectConstellationBrainSettings:{liveHealth:{enabled:false}}}),set:async(v)=>{window.__storedMetrics=v;}},onChanged:{addListener:(fn)=>listeners.push(fn)}},runtime:{sendMessage:async(msg)=>{window.__messageCalls++; if(msg.type==='PC_BRAIN_INGEST_BATCH') window.__brain.push(...msg.payload); if(msg.type==='PC_BRAIN_INGEST') window.__brain.push(msg.payload); if(msg.type==='PC_LIVE_HEALTH_CONTEXT') return {ok:true,settings:{enabled:false},network:{pending:0,observed:false},latestTurns:[],integrityFindings:[]}; return {ok:true};},onMessage:{addListener:(fn)=>{window.__pcMessageListener=fn;}}}};})();'''
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True,args=['--no-sandbox']); page=browser.new_page(viewport={'width':1280,'height':900}); errors=[]; page.on('pageerror',lambda exc: errors.append(str(exc)))
    page.set_content(fixture,wait_until='load');page.evaluate(mock);page.add_style_tag(content=css);page.add_script_tag(content=core);page.add_script_tag(content=brain);page.add_script_tag(content=health);page.add_script_tag(content=content);page.wait_for_timeout(1200)
    baseline=page.evaluate('''() => ({enabled:document.documentElement.dataset.projectConstellationEnabled,responsive:document.documentElement.dataset.projectConstellationResponsiveScroll,articles:document.querySelectorAll('article').length,first:document.body.innerText.includes('Turn 1'),last:document.body.innerText.includes('Turn 320'),scrollBehavior:getComputedStyle(document.documentElement).scrollBehavior,brainEvents:window.__brain.length,turnEvents:window.__brain.filter(x=>x.type==='TURN_UPSERT').length,provider:window.__brain.find(x=>x.type==='PROVIDER_SEEN')?.data?.id,messageCalls:window.__messageCalls})''')
    page.evaluate('''() => { const aside=document.createElement('aside'); aside.innerHTML='<a href="https://chatgpt.com/c/older-one">Older one</a><a href="https://chatgpt.com/c/older-two">Older two</a>'; document.body.appendChild(aside); }''')
    discover=page.evaluate('''() => new Promise(resolve=>window.__pcMessageListener({type:'PC_MANUAL_DISCOVER_CHATS',options:{speed:'test'}},null,resolve))''')
    deep=page.evaluate('''() => new Promise(resolve=>window.__pcMessageListener({type:'PC_MANUAL_FULL_CAPTURE',options:{speed:'test',maxSteps:2400}},null,resolve))''')
    reset=page.evaluate('''() => new Promise(resolve=>window.__pcMessageListener({type:'PC_RESET_METRICS'},null,resolve))''')
    after=page.evaluate('''() => ({articles:document.querySelectorAll('article').length,first:document.body.innerText.includes('Turn 1'),last:document.body.innerText.includes('Turn 320'),turnEvents:window.__brain.filter(x=>x.type==='TURN_UPSERT').length})''')
    result={'baseline':baseline,'discover':discover,'deep':deep,'after':after,'resetTasks':reset['metrics']['totalLongTasks'],'errors':errors};print(json.dumps(result,sort_keys=True));assert baseline['enabled']=='1' and baseline['responsive']=='1';assert baseline['articles']==320 and baseline['first'] and baseline['last'];assert baseline['scrollBehavior']=='auto';assert baseline['turnEvents']>=300;assert baseline['provider']=='chatgpt';assert baseline['messageCalls']<=8;assert discover['ok'] and discover['discovered']==2;assert deep['ok'] and deep['complete'] and deep['totalTurnsObserved']>=300;assert after['articles']==320 and after['first'] and after['last'];assert reset['metrics']['totalLongTasks']==0;assert not errors;browser.close()
