from playwright.sync_api import sync_playwright
import pathlib, os, json
root=pathlib.Path(os.environ.get('PROJECT_CONSTELLATION_ROOT','/mnt/data/project-constellation-v0120-work'))
core=(root/'src/core.js').read_text(); brain=(root/'src/brain-core.js').read_text(); health=(root/'src/health-core.js').read_text(); content=(root/'src/content.js').read_text(); pulse=(root/'src/pulse-ux.js').read_text(); css=(root/'src/styles.css').read_text()
page_html='''<!doctype html><html><head><meta charset="utf-8"><style>html,body{margin:0;background:#08090b;color:#eceff4;font-family:Inter,system-ui,sans-serif}main{max-width:900px;margin:0 auto;padding:70px 28px 180px}.turn{padding:18px 0;border-bottom:1px solid #20242b}.muted{color:#8c949f}.tool{margin:18px 0;padding:14px;border:1px solid #2c313a;border-radius:12px;background:#0f1115}.tool p{margin:0 0 10px;color:#c3c9d2}.tool button{display:block;background:transparent;color:#aeb6c2;border:0;padding:8px 0;font:inherit}.text-token-text-tertiary{color:#9aa4b4;padding:6px 0}.loading-shimmer-tertiary{color:#c7d2fe}h1{font-size:24px;font-weight:650}</style></head><body><main><h1>Combat compatibility hardening</h1><article class="turn" data-message-author-role="user" data-message-id="u1">Improve the compatibility layer without regressions.</article><article class="turn" data-message-author-role="assistant" data-message-id="a1">I’m auditing the runtime state and verifying the build.</article><div class="tool" id="toolBox" aria-busy="true"><p>Working through implementation steps</p><button aria-label="tool activity">Called tool</button><button aria-label="tool activity">Inspecting configuration reset and runtime changes</button></div><div class="group text-token-text-tertiary">Inspected current ChatGPT tool-card structure</div><div class="group text-token-text-tertiary"><span class="loading-shimmer-tertiary">Implementing truthful execution activity ledger</span></div></main></body></html>'''
mock=r'''(() => {
 const changes=[]; window.__brain=[]; window.__openCalls=[]; window.__branchCalls=[];
 const now=Date.now();
 window.__healthContext={ok:true,settings:{enabled:true,showHealthy:true,corner:'bottom-right',density:'compact',softStallMs:5000,hardStallMs:10000,deadStallMs:45000,hydrationGraceMs:1000,pollActiveMs:900,pollIdleMs:1500,toolWatchdogEnabled:true,capacityGuardEnabled:true,capacityWarningTurns:180,capacityHandoffTurns:260},capacity:{storedTurns:260},network:{pending:1,observed:true,lastStartAt:now,lastResponseAt:now,lastCompleteAt:0,lastErrorAt:0,lastStatusCode:200,rateLimited:false,streamLikely:true,inflight:[{id:'req-1',category:'response stream',method:'POST',startedAt:now}],events:[{id:'req-1',phase:'started',category:'response stream',method:'POST',status:0,startedAt:now,at:now,durationMs:0}]},latestTurns:[],integrityFindings:[],baseline:{latestVersion:'1.4.0'},chat:{coverage:'server-rendered-content',updatedAt:Date.now()}};
 window.ProjectConstellationProviders={detectProvider:()=>({id:'chatgpt',name:'ChatGPT',home:'https://chatgpt.com/'}),chatIdFromUrl:()=> 'chatgpt:live-health',isLikelyChatUrl:()=>true,canonicalChatUrl:(u)=>u,classifyExternalUrl:(u)=>({kind:'external',provider:'example.com',external:true,url:u}),hashString:(value)=>{let h=2166136261;for(const ch of String(value||'')){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return (h>>>0).toString(36);}};
 const vaultRegression={active:true,title:'Saved output is missing from this page',detail:'1 shortened response · 1 media item · 1 link',missingTurns:[],changedTurns:[{turnId:'chatgpt:live-health:a1'}],missingAssets:1,missingLinks:1,missingCodeBlocks:1};
 const vaultItem={id:'chatgpt:live-health:a1',chatId:'chatgpt:live-health',role:'assistant',ordinal:1,text:'Complete production answer\nThis is the complete saved production answer with the final build, generated image, code, and recovery instructions.\nRelease archive verified\nRecovery checkpoint saved\nOpen full release',formattedText:'## Complete production answer\n\nThis is the complete saved production answer with the **final build**, generated image, code, and recovery instructions.\n\n- Release archive verified\n- Recovery checkpoint saved\n\n[Open full release](https://example.com/constellation-release.zip)',links:[{href:'https://example.com/constellation-release.zip',text:'Full release build'}],assets:[{id:'saved-image',kind:'image',url:'https://example.com/constellation.png',alt:'Generated constellation image',width:1024,height:1024}],codeBlocks:[{language:'json',text:'{"saved":true,"complete":true}'}],revisionCount:2,current:{excerpt:'Called tool\nCalled tool\nSearched 2 websites',textLength:42},affected:true};
 window.chrome={storage:{local:{get:async()=>({projectConstellationPerformanceSettings:{enabled:true,responsiveScrolling:true,adaptiveMotionRelief:false},projectConstellationBrainSettings:{liveHealth:window.__healthContext.settings,approvalAutopilot:{enabled:false,acknowledged:false}},projectConstellationPerformanceMetrics:{}}),set:async()=>{}},onChanged:{addListener:(fn)=>changes.push(fn)}},runtime:{sendMessage:async(msg)=>{if(msg.type==='PC_BRAIN_INGEST_BATCH'){window.__brain.push(...(msg.payload||[]));return {ok:true};}if(msg.type==='PC_BRAIN_INGEST'){window.__brain.push(msg.payload);return {ok:true};}if(msg.type==='PC_LIVE_HEALTH_CONTEXT')return structuredClone(window.__healthContext);if(msg.type==='PC_OUTPUT_OBSERVE')return {ok:true,regression:window.__healthContext.chat?.outputRegression||null};if(msg.type==='PC_OUTPUT_COMPARE')return {ok:true,chat:{id:'chatgpt:live-health',title:'Combat compatibility hardening',url:'https://chatgpt.com/c/live-health'},regression:vaultRegression,items:[vaultItem],files:[{id:'build',name:'Project-Constellation-v0.14.0.zip',href:'https://example.com/constellation-release.zip',kind:'release'}],total:1,offset:0,hasMore:false,nextOffset:1,markdown:'# Project Constellation Output Vault\n\nComplete saved production answer'};if(msg.type==='PC_OUTPUT_TURN_REVISIONS')return {ok:true,turn:{bestRevisionId:'rev-rich'},revisions:[{id:'rev-poor',capturedAt:Date.now(),richnessScore:42,text:'Called tool'},{id:'rev-rich',capturedAt:Date.now()-1000,richnessScore:2800,text:vaultItem.text}]};if(msg.type==='PC_OPEN_CONSTELLATION_PAGE'){window.__openCalls.push(msg);return {ok:true};}if(msg.type==='PC_BRANCH_CHAT'){window.__branchCalls.push(msg);return {ok:true,branchId:'branch:test',checkpointId:'handoff:chatgpt:live-health:branch',targetTabId:88};}if(msg.type==='PC_BRANCH_CONTINUATION_CLAIM')return {ok:false,state:'none'};if(msg.type==='PC_PREPARE_CHAT_HANDOFF')return {ok:true,checkpointId:'handoff:chatgpt:live-health:test',markdown:'# Project Constellation Safe Handoff\n\nSmoke checkpoint',drive:{attempted:true,verified:true,status:'roundtrip-verified'}};return {ok:true};},onMessage:{addListener:(fn)=>window.__pcMessageListener=fn}}};
})();'''
with sync_playwright() as p:
    launch={'headless':True,'args':['--no-sandbox']}
    chromium=os.environ.get('PROJECT_CONSTELLATION_CHROMIUM','').strip()
    if chromium: launch['executable_path']=chromium
    browser=p.chromium.launch(**launch)
    page=browser.new_page(viewport={'width':1440,'height':920}); errors=[]; page.on('pageerror',lambda exc: errors.append(str(exc)))
    page.set_content(page_html,wait_until='domcontentloaded')
    page.evaluate(mock);page.add_style_tag(content=css);page.add_script_tag(content=core);page.add_script_tag(content=brain);page.add_script_tag(content=health);page.add_script_tag(content=content);page.add_script_tag(content=pulse)
    page.wait_for_timeout(2600)
    active=page.evaluate('''() => { const h=document.getElementById('projectConstellationHealthHud');const s=h?.shadowRoot;return {exists:!!h,state:s?.getElementById('pcHealthTitle')?.textContent,network:s?.getElementById('pcHealthNetwork')?.textContent,activity:s?.getElementById('pcHealthActivity')?.textContent,tool:s?.getElementById('pcHealthTool')?.textContent,project:s?.getElementById('pcHealthProject')?.textContent,capacity:s?.getElementById('pcHealthCapacity')?.textContent,handoffHidden:s?.getElementById('pcHealthHandoff')?.hidden,branchText:s?.getElementById('pcHealthBranch')?.textContent,branchUrgent:s?.getElementById('pcHealthBranch')?.dataset.urgent,visible:h?.dataset.visible,collapsed:h?.dataset.collapsed,level:h?.dataset.level,healthState:h?.dataset.state,nowTitle:s?.getElementById('pcHealthNowTitle')?.textContent,proof:s?.getElementById('pcHealthProof')?.textContent,timeline:[...s?.querySelectorAll('.eventTitle')||[]].map(n=>n.textContent),articles:document.querySelectorAll('article').length}; }''')
    assert active['exists'] and active['visible']=='1' and active['state'].startswith('Tool working') and active['healthState']=='tool-running', active
    assert 'agent request' in active['network'] and active['activity'] in ['editing','inspecting','tool call','executing','retrieving'] and 'step' in active['tool'] and '1.4.0' in active['project']
    assert 'secure' in active['capacity'] and active['handoffHidden'] is False and active['level']=='danger'
    assert 'Branch' in active['branchText'] and active['branchUrgent']=='1'
    assert active['collapsed']=='0' and active['nowTitle']=='Implementing truthful execution activity ledger'
    assert 'HIGH observable confidence' in active['proof'] and any('Started response stream' in row for row in active['timeline'])
    collapsed_branch=page.evaluate('''() => { const h=document.getElementById('projectConstellationHealthHud');const s=h.shadowRoot;s.getElementById('pcHealthCollapse').click();const q=s.getElementById('pcHealthBranchQuick');const result={collapsed:h.dataset.collapsed,visible:getComputedStyle(q).display!=='none',urgent:q.dataset.urgent,label:q.getAttribute('aria-label')};s.getElementById('pcHealthCollapse').click();return result; }''')
    assert collapsed_branch=={'collapsed':'1','visible':True,'urgent':'1','label':'Branch and continue in a new chat'}
    capacity_shot=pathlib.Path(os.environ.get('PROJECT_CONSTELLATION_CAPACITY_SCREENSHOT',str(root/'dist/execution-pulse-v014.png'))); capacity_shot.parent.mkdir(parents=True,exist_ok=True); page.screenshot(path=str(capacity_shot),full_page=False)
    page.evaluate("document.getElementById('projectConstellationHealthHud').shadowRoot.getElementById('pcHealthBranch').click()")
    page.wait_for_timeout(120)
    assert page.evaluate('window.__branchCalls.length')==1
    # Repeated generic "Called tool" rows must count as real timeline progress instead of looking frozen merely because the label repeats.
    initial_steps=int(active['tool'].split()[0])
    for idx in range(3):
        page.evaluate('''(idx) => { const b=document.createElement('button');b.setAttribute('aria-label','tool activity');b.textContent='Called tool';b.dataset.step=String(idx);document.getElementById('toolBox').appendChild(b); }''', idx)
        page.wait_for_timeout(1050)
    pulse=page.evaluate('''() => { const h=document.getElementById('projectConstellationHealthHud');const s=h.shadowRoot;return {state:h.dataset.state,title:s.getElementById('pcHealthTitle').textContent,tool:s.getElementById('pcHealthTool').textContent,activity:s.getElementById('pcHealthActivity').textContent,mini:s.getElementById('pcHealthMini').textContent}; }''')
    assert pulse['state']=='tool-running' and int(pulse['tool'].split()[0]) >= initial_steps + 3
    assert 'live request' in pulse['mini'] and 'Implementing truthful execution activity ledger' in pulse['mini'] and pulse['activity']
    # A tool card that remains on-screen and busy with no fresh request or DOM/tool progress must become explicitly stuck.
    page.evaluate('''() => { const now=Date.now();window.__healthContext={...window.__healthContext,capacity:{storedTurns:0},network:{pending:0,observed:true,oldestPendingAt:0,lastStartAt:now-20000,lastResponseAt:now-19000,lastCompleteAt:now-18000,lastErrorAt:0,lastStatusCode:200,rateLimited:false,streamLikely:false}}; }''')
    page.wait_for_timeout(11200)
    stuck=page.evaluate('''() => { const h=document.getElementById('projectConstellationHealthHud');const s=h.shadowRoot;return {state:h.dataset.state,title:s.getElementById('pcHealthTitle').textContent,detail:s.getElementById('pcHealthDetail').textContent,network:s.getElementById('pcHealthNetwork').textContent,tool:s.getElementById('pcHealthTool').textContent,level:h.dataset.level,branchText:s.getElementById('pcHealthBranch').textContent,branchUrgent:s.getElementById('pcHealthBranch').dataset.urgent}; }''')
    assert stuck['state']=='tool-stalled' and stuck['title'].startswith('Tool call looks stuck') and stuck['network']=='quiet' and stuck['level']=='danger'
    assert 'no live provider request' in stuck['detail'].lower() and 'step' in stuck['tool']
    assert 'Branch' in stuck['branchText'] and stuck['branchUrgent']=='0'
    page.evaluate("document.getElementById('projectConstellationHealthHud').shadowRoot.getElementById('pcHealthHandoff').click()")
    page.wait_for_timeout(250)
    handoff_label=page.evaluate("document.getElementById('projectConstellationHealthHud').shadowRoot.getElementById('pcHealthHandoff').textContent")
    assert 'Handoff copied' in handoff_label and 'Drive verified' in handoff_label
    # Now simulate a completed-looking but stale revision from an authoritative full export.
    page.evaluate('''() => { document.getElementById('toolBox').remove(); window.__healthContext={...window.__healthContext,network:{pending:0,observed:true,lastStartAt:Date.now()-12000,lastResponseAt:Date.now()-11000,lastCompleteAt:Date.now()-10000,lastErrorAt:0,lastStatusCode:200,rateLimited:false,streamLikely:false},chat:{coverage:'full-export',source:'official-export',updatedAt:Date.now()+5000},latestTurns:[{id:'chatgpt:live-health:remote-a2',messageId:'remote-a2',ordinal:99,textHash:'definitely-newer'}]}; }''')
    page.evaluate('''() => new Promise(resolve=>window.__pcMessageListener({type:'PC_RESCAN'},null,resolve))''')
    page.wait_for_timeout(2800)
    stale=page.evaluate('''() => { const h=document.getElementById('projectConstellationHealthHud');const s=h.shadowRoot;return {state:s.getElementById('pcHealthTitle').textContent,detail:s.getElementById('pcHealthDetail').textContent,page:s.getElementById('pcHealthPage').textContent,refreshHidden:s.getElementById('pcHealthRefresh').hidden,level:h.dataset.level}; }''')
    assert stale['state']=='This tab is behind' and stale['page']=='behind' and stale['refreshHidden'] is False and stale['level']=='critical'
    # A later provider rewrite that drops the rich final response must surface the durable Output Vault immediately.
    page.evaluate('''() => { window.__healthContext={...window.__healthContext,chat:{coverage:'server-rendered-content',source:'mounted-dom',updatedAt:Date.now(),outputRegression:{active:true,title:'Saved output is missing from this page',detail:'1 shortened response · 1 media item · 1 link',missingTurns:[],changedTurns:[{turnId:'chatgpt:live-health:a1'}],missingAssets:1,missingLinks:1,missingCodeBlocks:1}},latestTurns:[]}; }''')
    page.wait_for_function("() => { const h=document.getElementById('projectConstellationHealthHud'); return h?.dataset.state==='output-regressed' && h?.dataset.pcxOutputSecondary==='1'; }", timeout=8000)
    regressed=page.evaluate('''() => { const h=document.getElementById('projectConstellationHealthHud');const s=h.shadowRoot;const sig=s.getElementById('pcxVaultSignal');return {state:h.dataset.state,main:h.dataset.pcxMainState,secondary:h.dataset.pcxOutputSecondary,title:s.getElementById('pcHealthTitle').textContent,page:s.getElementById('pcHealthPage').textContent,vaultUrgent:s.getElementById('pcHealthVault').dataset.urgent,quickVaultLabel:s.getElementById('pcHealthVaultQuick').getAttribute('aria-label'),signal:sig?.dataset.visible,signalText:sig?.textContent}; }''')
    assert regressed['state']=='output-regressed' and regressed['main']=='completed' and regressed['secondary']=='1'
    assert regressed['title']=='Chat complete' and regressed['page']=='vault check'
    assert regressed['vaultUrgent']=='0' and regressed['quickVaultLabel']=='Open Output Vault' and regressed['signal']=='1' and 'Output Vault' in regressed['signalText']
    page.evaluate("document.getElementById('projectConstellationHealthHud').shadowRoot.getElementById('pcHealthVault').click()")
    page.wait_for_timeout(180)
    vault=page.evaluate('''() => { const h=document.getElementById('projectConstellationOutputVault');const s=h?.shadowRoot;const p=document.getElementById('projectConstellationHealthHud');const vr=s?.querySelector('.vault')?.getBoundingClientRect();const pr=p?.shadowRoot?.querySelector('.hud')?.getBoundingClientRect();return {exists:!!h,title:s?.getElementById('pcVaultTitle')?.textContent,status:s?.getElementById('pcVaultStatus')?.textContent,alert:s?.getElementById('pcVaultAlert')?.dataset.active,text:s?.textContent||'',links:[...s?.querySelectorAll('a.resource')||[]].map(a=>a.href),cards:s?.querySelectorAll('.turn').length,collapsed:h?.dataset.collapsed,expanded:h?.dataset.expanded,pulseCollapsed:p?.dataset.collapsed,stacked:!!vr&&!!pr&&vr.bottom<=pr.top-6,reader:s?.getElementById('pcVaultReader')?.getAttribute('aria-pressed'),rich:s?.querySelectorAll('.richText').length,heading:s?.querySelector('.richText h2')?.textContent,activity:s?.querySelector('.activityGroup summary')?.textContent}; }''')
    assert vault['exists'] and vault['title']=='Combat compatibility hardening' and vault['alert']=='1' and vault['cards']==2
    assert 'complete saved production answer' in vault['text'] and 'Project-Constellation-v0.14.0.zip' in vault['text'] and 'Generated constellation image' in vault['text']
    assert vault['pulseCollapsed']=='1' and vault['stacked'] and vault['reader']=='true' and vault['rich']>=2
    assert vault['heading']=='Complete production answer' and '3 steps' in vault['activity']
    assert any('constellation-release.zip' in link for link in vault['links'])
    view_modes=page.evaluate('''() => { const h=document.getElementById('projectConstellationOutputVault');const s=h.shadowRoot;s.getElementById('pcVaultRaw').click();const raw={pressed:s.getElementById('pcVaultRaw').getAttribute('aria-pressed'),rawBlocks:s.querySelectorAll('.savedText,.currentText').length};s.getElementById('pcVaultReader').click();return {...raw,reader:s.getElementById('pcVaultReader').getAttribute('aria-pressed'),richBlocks:s.querySelectorAll('.richText').length}; }''')
    assert view_modes['pressed']=='true' and view_modes['rawBlocks']>=2 and view_modes['reader']=='true' and view_modes['richBlocks']>=2
    vault_modes=page.evaluate('''() => { const h=document.getElementById('projectConstellationOutputVault');const s=h.shadowRoot;s.getElementById('pcVaultCollapse').click();const collapsed=h.dataset.collapsed;s.getElementById('pcVaultCollapse').click();s.getElementById('pcVaultExpand').click();return {collapsed,restored:h.dataset.collapsed,expanded:h.dataset.expanded}; }''')
    assert vault_modes=={'collapsed':'1','restored':'0','expanded':'1'}
    page.wait_for_timeout(80)
    assert page.evaluate('''() => { const v=document.getElementById('projectConstellationOutputVault').shadowRoot.querySelector('.vault').getBoundingClientRect();const p=document.getElementById('projectConstellationHealthHud').shadowRoot.querySelector('.hud').getBoundingClientRect();return v.bottom<=p.top-6; }''')
    page.evaluate("document.getElementById('projectConstellationOutputVault').shadowRoot.querySelector('.turn .miniBtn:nth-of-type(2)')?.click()")
    page.wait_for_timeout(120)
    assert 'Captured revision history' in page.evaluate("document.getElementById('projectConstellationOutputVault').shadowRoot.textContent")
    # Health settings must open the exact Constellation health section rather than a generic page.
    page.evaluate("document.getElementById('projectConstellationHealthHud').shadowRoot.getElementById('pcHealthSettings').click()")
    page.wait_for_timeout(80)
    open_call=page.evaluate('window.__openCalls.at(-1)')
    assert open_call and open_call['view']=='attention' and open_call['focus']=='live-health'
    screenshot=pathlib.Path(os.environ.get('PROJECT_CONSTELLATION_HEALTH_SCREENSHOT',str(root/'dist/live-health-v014.png'))); screenshot.parent.mkdir(parents=True,exist_ok=True); page.screenshot(path=str(screenshot),full_page=False)
    result={'active':active,'pulse':pulse,'stuck':stuck,'stale':stale,'regressed':regressed,'vault':vault,'vaultModes':vault_modes,'openCall':open_call,'handoffLabel':handoff_label,'brainEvents':page.evaluate('window.__brain.length'),'errors':errors,'screenshot':str(screenshot),'capacityScreenshot':str(capacity_shot)}
    print(json.dumps(result,sort_keys=True)); assert not errors
    browser.close()
