from playwright.sync_api import sync_playwright
import json,pathlib,re,os
root=pathlib.Path(os.environ.get('PROJECT_CONSTELLATION_ROOT','/mnt/data/project-constellation'));html=(root/'popup.html').read_text();html=re.sub(r'<link[^>]+popup\.css[^>]*>','',html);html=re.sub(r'<link[^>]+popup-pulse\.css[^>]*>','',html);html=re.sub(r'<script[^>]+popup\.js[^>]*></script>','',html);css=(root/'popup.css').read_text()+'\n'+(root/'popup-pulse.css').read_text();js=(root/'popup.js').read_text()
mock=r'''window.__created=[];window.__stored={projectConstellationPerformanceSettings:{enabled:true,responsiveScrolling:true,adaptiveMotionRelief:false},projectConstellationPulseUxSettings:{statusPinEnabled:true,outputWarningsEnabled:true,outputWarningStrictness:'balanced'}};window.chrome={runtime:{id:'pc-test',getURL:(p)=>'chrome-extension://pc-test/'+p,sendMessage:async(msg)=>msg.type==='PC_BRAIN_COUNTS'?{ok:true,counts:{statusCounts:{idle:6,running:2,paused:0,'waiting-user':0,'blocked-approval':0,'refresh-required':0,'rate-limited':0,errored:1,stalled:0,'auth-required':0,unavailable:0,archived:1},recentChats:[{id:'a',status:'running',title:'Live build verification',url:'https://chatgpt.com/c/live',updatedAt:Date.now()},{id:'s',status:'errored',title:'Stale OAuth acceptance',url:'https://chatgpt.com/c/stale',updatedAt:Date.now()-1000},{id:'c',status:'idle',title:'Completed compatibility pass',url:'https://chatgpt.com/c/done',updatedAt:Date.now()-2000}]}}:{ok:true}},storage:{local:{get:async(keys)=>{if(Array.isArray(keys))return Object.fromEntries(keys.map(k=>[k,window.__stored[k]]));return {[keys]:window.__stored[keys]};},set:async(v)=>{Object.assign(window.__stored,v);window.__lastStored=v;}}},tabs:{query:async()=>[{id:7,windowId:1,url:'https://chatgpt.com/c/test'}],sendMessage:async(id,msg)=>({provider:{id:'chatgpt',name:'ChatGPT'},chat:{id:'chatgpt:test',status:'running'},metrics:{totalLongTasks:msg.type==='PC_RESET_METRICS'?0:4,maxLongTaskMs:110,route:'/c/test'},pressure:{pressure:'normal'},capabilities:{constellationCapture:true}}),create:async(o)=>{window.__created.push(o);return {id:8};}},sidePanel:{open:async()=>{throw new Error('side panel unavailable');}}};window.close=()=>{window.__closed=true;};'''
with sync_playwright() as p:
    executable=os.environ.get('PROJECT_CONSTELLATION_CHROMIUM') or None
    browser=p.chromium.launch(headless=True,args=['--no-sandbox'],executable_path=executable);page=browser.new_page(viewport={'width':420,'height':900});errors=[];page.on('pageerror',lambda exc:errors.append(str(exc)));page.set_content(html,wait_until='load');page.evaluate(mock);page.add_style_tag(content=css);page.add_script_tag(content=js);page.wait_for_timeout(300)
    before=page.evaluate('''()=>({pressure:document.querySelector('#pressure').textContent,tasks:document.querySelector('#longTasks').textContent,provider:document.querySelector('#provider').textContent,state:document.querySelector('#chatState').textContent,enabled:document.querySelector('#enabled').checked,pin:document.querySelector('#statusPinEnabled').checked,warnings:document.querySelector('#outputWarningsEnabled').checked,strictness:document.querySelector('#outputWarningStrictness').value,active:document.querySelector('#activeCount').textContent,stale:document.querySelector('#staleCount').textContent,completed:document.querySelector('#completedCount').textContent,activeLatest:document.querySelector('#activeLatest').textContent,staleLatest:document.querySelector('#staleLatest').textContent,completedLatest:document.querySelector('#completedLatest').textContent,pulseHidden:document.querySelector('#chatPulse').hidden})''')
    page.locator('#activeSummary').click();page.wait_for_timeout(20);page.locator('#openHome').click();page.wait_for_timeout(20);page.locator('#openConstellation').click();page.wait_for_timeout(20);page.locator('#openAccounts').click();page.wait_for_timeout(20);created=page.evaluate('window.__created')
    page.locator('#outputWarningStrictness').select_option('strict');page.wait_for_timeout(20);strict_saved=page.evaluate("window.__stored.projectConstellationPulseUxSettings.outputWarningStrictness")
    page.locator('#statusPinEnabled').uncheck();page.wait_for_timeout(20);pin_state=page.evaluate('''()=>({stored:window.__stored.projectConstellationPulseUxSettings.statusPinEnabled,hidden:document.querySelector('#chatPulse').hidden})''')
    page.locator('#resetMetrics').click();page.wait_for_timeout(50);after=page.locator('#longTasks').text_content();page.screenshot(path=os.environ.get('PROJECT_CONSTELLATION_POPUP_SCREENSHOT','/mnt/data/project-constellation/dist/popup-smoke.png'));print(json.dumps({'before':before,'created':created,'strict_saved':strict_saved,'pin_state':pin_state,'after':after,'errors':errors},sort_keys=True));assert before['pressure']=='normal' and before['tasks']=='4' and before['provider']=='ChatGPT' and before['state']=='running' and before['enabled'];assert before['pin'] and before['warnings'] and before['strictness']=='balanced' and not before['pulseHidden'];assert before['active']=='2' and before['stale']=='1' and before['completed']=='7';assert before['activeLatest']=='Live build verification' and before['staleLatest']=='Stale OAuth acceptance' and before['completedLatest']=='Completed compatibility pass';assert any(x['url']=='https://chatgpt.com/c/live' for x in created);assert any(x['url'].endswith('/home.html') for x in created);assert any(x['url'].endswith('/sidepanel.html') for x in created);assert any('home.html?view=connections' in x['url'] for x in created);assert strict_saved=='strict';assert pin_state=={'stored':False,'hidden':True};assert after=='0';assert not errors;browser.close()