from playwright.sync_api import sync_playwright
import pathlib, os, json
root=pathlib.Path(os.environ.get('PROJECT_CONSTELLATION_ROOT','/mnt/data/project-constellation'))
script=(root/'src/pulse-ux.js').read_text()
html='''<!doctype html><html><head><meta charset="utf-8"></head><body><main>Provider page</main></body></html>'''
mock=r'''(() => {
 window.__opened=[];window.__changes=[];window.__focused=[];
 window.__settings={statusPinEnabled:true,outputWarningsEnabled:true,outputWarningStrictness:'balanced'};
 window.__context={ok:true,chat:{id:'chatgpt:test',status:'idle',statusDetail:'',outputRegression:{active:true,title:'Saved output is missing from this page',detail:'1 missing response',missingTurns:[{turnId:'tool-row',ordinal:7,textLength:150,savedScore:60,assetCount:0,linkCount:0,codeBlocks:0}],changedTurns:[],missingAssets:0,missingLinks:0,missingCodeBlocks:0}}};
 window.chrome={runtime:{sendMessage:async(msg)=>{if(msg.type==='PC_LIVE_CHAT_PULSE')return {ok:true,openChatTabs:7,counts:{active:2,stale:1,completed:4},groups:{active:[{tabId:1,windowId:1,title:'Active research',providerName:'ChatGPT',status:'running',generation:{phase:'searching'}},{tabId:2,windowId:1,title:'Active build',providerName:'ChatGPT',status:'running',generation:{phase:'building'}}],stale:[{tabId:3,windowId:1,title:'Approval needed',providerName:'ChatGPT',status:'blocked-approval'}],completed:[{tabId:4,windowId:1,title:'Completed A',providerName:'ChatGPT',status:'idle',context:{projectName:'Project Constellation',taskHint:'Verify the final browser regression suite'},tabGroup:{id:99,title:'My Work',managed:false}},{tabId:5,windowId:1,title:'Completed B',providerName:'ChatGPT',status:'idle'},{tabId:6,windowId:1,title:'Completed C',providerName:'ChatGPT',status:'idle'},{tabId:7,windowId:1,title:'Completed D',providerName:'ChatGPT',status:'idle'}]}};if(msg.type==='PC_LIVE_HEALTH_CONTEXT')return structuredClone(window.__context);if(msg.type==='PC_FOCUS_LIVE_CHAT'){window.__focused.push(msg);return {ok:true};}if(msg.type==='PC_OPEN_CONSTELLATION_PAGE'){window.__opened.push(msg);return {ok:true};}return {ok:true};}},storage:{local:{get:async()=>({projectConstellationPulseUxSettings:structuredClone(window.__settings)}),set:async(v)=>{window.__settings={...window.__settings,...(v.projectConstellationPulseUxSettings||{})};}},onChanged:{addListener:(fn)=>window.__changes.push(fn)}}};
})();'''
hosts=r'''(() => {
 const h=document.createElement('div');h.id='projectConstellationHealthHud';h.dataset.state='output-regressed';h.dataset.level='critical';h.dataset.collapsed='1';h.dataset.visible='1';
 const s=h.attachShadow({mode:'open'});s.innerHTML=`<section class="hud"><div class="top"><div class="brand"><div class="eyebrow">CONSTELLATION</div><div class="state" id="pcHealthTitle">Saved output is missing</div><div class="substate" id="pcHealthMini">1 missing response</div></div><div class="tools"><button id="pcHealthVaultQuick" class="quickVault" data-urgent="1">V</button></div></div><div class="body"><p id="pcHealthDetail">Output regression detail</p><div class="metrics"><div><strong id="pcHealthPage">output missing</strong></div></div></div><div class="actions"><button id="pcHealthVault" class="btn vault" data-urgent="1">Output Vault</button></div></section>`;document.documentElement.appendChild(h);
 const v=document.createElement('div');v.id='projectConstellationOutputVault';v.dataset.collapsed='0';const vs=v.attachShadow({mode:'open'});vs.innerHTML=`<section class="vault"><div class="alert" id="pcVaultAlert" data-active="1"><strong id="pcVaultAlertTitle">Saved output is missing</strong><span id="pcVaultAlertDetail">1 missing response</span></div><div class="workspace"><aside class="rail"><label class="filter">Filter</label><p class="railNote">Existing note</p></aside><main><div id="pcVaultStatus">Comparing output.</div></main></div></section>`;document.documentElement.appendChild(v);
})();'''
with sync_playwright() as p:
    executable=os.environ.get('PROJECT_CONSTELLATION_CHROMIUM') or None
    browser=p.chromium.launch(headless=True,args=['--no-sandbox'],executable_path=executable);page=browser.new_page(viewport={'width':1200,'height':800});errors=[];page.on('pageerror',lambda exc:errors.append(str(exc)));page.set_content(html,wait_until='domcontentloaded');page.evaluate(mock);page.add_script_tag(content=script);page.evaluate(hosts);page.wait_for_timeout(450)
    balanced=page.evaluate(r'''() => {const h=document.getElementById('projectConstellationHealthHud');const s=h.shadowRoot;const v=document.getElementById('projectConstellationOutputVault').shadowRoot;const pin=s.getElementById('pcxChatPin');return {title:s.getElementById('pcHealthTitle').textContent,mini:s.getElementById('pcHealthMini').textContent,page:s.getElementById('pcHealthPage').textContent,signal:s.getElementById('pcxVaultSignal').dataset.visible,vaultUrgent:s.getElementById('pcHealthVault').dataset.urgent,pinText:pin.textContent.replace(/\s+/g,' ').trim(),pinDisplay:getComputedStyle(pin).display,pinSetting:h.dataset.pcxStatusPin,mainState:h.dataset.pcxMainState,alert:v.getElementById('pcVaultAlert').dataset.active,strictness:v.getElementById('pcxVaultStrictness').value,note:v.getElementById('pcxVaultPolicyNote').textContent};}''')
    assert balanced['title']=='Chat complete' and balanced['page']=='current' and balanced['signal']=='0' and balanced['vaultUrgent']=='0', balanced
    assert balanced['pinSetting']=='1' and balanced['pinDisplay']=='flex' and 'Active2' in balanced['pinText'] and 'Stale1' in balanced['pinText'] and 'Done4' in balanced['pinText'], balanced
    assert balanced['mainState']=='completed' and balanced['alert']=='0' and balanced['strictness']=='balanced' and 'suppressed' in balanced['note'].lower(), balanced
    page.evaluate("document.getElementById('projectConstellationOutputVault').shadowRoot.getElementById('pcxVaultStrictness').value='strict';document.getElementById('projectConstellationOutputVault').shadowRoot.getElementById('pcxVaultStrictness').dispatchEvent(new Event('change',{bubbles:true}));")
    page.wait_for_timeout(250)
    strict=page.evaluate('''() => {const s=document.getElementById('projectConstellationHealthHud').shadowRoot;const v=document.getElementById('projectConstellationOutputVault').shadowRoot;return {signal:s.getElementById('pcxVaultSignal').dataset.visible,signalText:s.getElementById('pcxVaultSignal').textContent,page:s.getElementById('pcHealthPage').textContent,alert:v.getElementById('pcVaultAlert').dataset.active,alertTitle:v.getElementById('pcVaultAlertTitle').textContent,stored:window.__settings.outputWarningStrictness};}''')
    assert strict['signal']=='1' and '1 difference' in strict['signalText'] and strict['page']=='vault check', strict
    assert strict['alert']=='1' and strict['alertTitle']=='Saved/page mismatch detected' and strict['stored']=='strict', strict
    page.evaluate("document.getElementById('projectConstellationHealthHud').shadowRoot.querySelector('#pcxChatPin [data-bucket=\"completed\"]').click()")
    page.wait_for_timeout(100);nav=page.evaluate('''() => {const s=document.getElementById('projectConstellationHealthHud').shadowRoot;return {visible:s.getElementById('pcxChatList').dataset.visible,rows:s.querySelectorAll('#pcxChatList .pcx-chat-list-row').length,title:s.querySelector('#pcxChatList .pcx-chat-list-title').textContent,context:s.querySelector('#pcxChatList .pcx-list-context').textContent,meta:s.querySelector('#pcxChatList .pcx-list-meta').textContent};}''');assert nav['visible']=='1' and nav['rows']==4 and nav['title']=='Completed chats · 4',nav;assert nav['context']=='Last task · Verify the final browser regression suite',nav;assert 'Project: Project Constellation' in nav['meta'],nav
    page.evaluate("document.getElementById('projectConstellationHealthHud').shadowRoot.querySelector('#pcxChatList .pcx-chat-list-row').click()")
    page.wait_for_timeout(40);assert page.evaluate('window.__focused.at(-1).tabId')==4
    shot=pathlib.Path(os.environ.get('PROJECT_CONSTELLATION_HEALTH_SCREENSHOT',str(root/'dist/pulse-ux-smoke.png')));shot.parent.mkdir(parents=True,exist_ok=True);page.screenshot(path=str(shot),full_page=False)
    print(json.dumps({'balanced':balanced,'strict':strict,'nav':nav,'errors':errors},sort_keys=True));assert not errors;browser.close()