from playwright.sync_api import sync_playwright
import pathlib, os, json
root=pathlib.Path(os.environ.get('PROJECT_CONSTELLATION_ROOT','/mnt/data/project-constellation'))
script=(root/'src/pulse-ux.js').read_text()
html='''<!doctype html><html><head><meta charset="utf-8"></head><body><main>Provider page</main></body></html>'''
mock=r'''(() => {
 window.__opened=[];window.__changes=[];
 window.__settings={statusPinEnabled:true,outputWarningsEnabled:true,outputWarningStrictness:'balanced'};
 window.__context={ok:true,chat:{id:'chatgpt:test',status:'idle',statusDetail:'',outputRegression:{active:true,title:'Saved output is missing from this page',detail:'1 missing response',missingTurns:[{turnId:'tool-row',ordinal:7,textLength:150,savedScore:60,assetCount:0,linkCount:0,codeBlocks:0}],changedTurns:[],missingAssets:0,missingLinks:0,missingCodeBlocks:0}}};
 window.chrome={runtime:{sendMessage:async(msg)=>{if(msg.type==='PC_BRAIN_COUNTS')return {ok:true,counts:{statusCounts:{idle:4,running:2,paused:0,'waiting-user':0,'blocked-approval':0,'refresh-required':0,'rate-limited':0,errored:1,stalled:0,'auth-required':0,unavailable:0,archived:0},recentChats:[]}};if(msg.type==='PC_LIVE_HEALTH_CONTEXT')return structuredClone(window.__context);if(msg.type==='PC_OPEN_CONSTELLATION_PAGE'){window.__opened.push(msg);return {ok:true};}return {ok:true};}},storage:{local:{get:async()=>({projectConstellationPulseUxSettings:structuredClone(window.__settings)}),set:async(v)=>{window.__settings={...window.__settings,...(v.projectConstellationPulseUxSettings||{})};}},onChanged:{addListener:(fn)=>window.__changes.push(fn)}}};
})();'''
hosts=r'''(() => {
 const h=document.createElement('div');h.id='projectConstellationHealthHud';h.dataset.state='output-regressed';h.dataset.level='critical';h.dataset.collapsed='1';h.dataset.visible='1';
 const s=h.attachShadow({mode:'open'});s.innerHTML=`<section class="hud"><div class="top"><div class="brand"><div class="eyebrow">CONSTELLATION</div><div class="state" id="pcHealthTitle">Saved output is missing</div><div class="substate" id="pcHealthMini">1 missing response</div></div><div class="tools"><button id="pcHealthVaultQuick" class="quickVault" data-urgent="1">V</button></div></div><div class="body"><p id="pcHealthDetail">Output regression detail</p><div class="metrics"><div><strong id="pcHealthPage">output missing</strong></div></div></div><div class="actions"><button id="pcHealthVault" class="btn vault" data-urgent="1">Output Vault</button></div></section>`;document.documentElement.appendChild(h);
 const v=document.createElement('div');v.id='projectConstellationOutputVault';v.dataset.collapsed='0';const vs=v.attachShadow({mode:'open'});vs.innerHTML=`<section class="vault"><div class="alert" id="pcVaultAlert" data-active="1"><strong id="pcVaultAlertTitle">Saved output is missing</strong><span id="pcVaultAlertDetail">1 missing response</span></div><div class="workspace"><aside class="rail"><label class="filter">Filter</label><p class="railNote">Existing note</p></aside><main><div id="pcVaultStatus">Comparing output.</div></main></div></section>`;document.documentElement.appendChild(v);
})();'''
with sync_playwright() as p:
    executable=os.environ.get('PROJECT_CONSTELLATION_CHROMIUM') or None
    browser=p.chromium.launch(headless=True,args=['--no-sandbox'],executable_path=executable);page=browser.new_page(viewport={'width':1200,'height':800});errors=[];page.on('pageerror',lambda exc:errors.append(str(exc)));page.set_content(html,wait_until='domcontentloaded');page.evaluate(mock);page.add_script_tag(content=script);page.evaluate(hosts);page.wait_for_timeout(450)
    balanced=page.evaluate(r'''() => {const h=document.getElementById('projectConstellationHealthHud');const s=h.shadowRoot;const v=document.getElementById('projectConstellationOutputVault').shadowRoot;const pin=s.getElementById('pcxChatPin');return {title:s.getElementById('pcHealthTitle').textContent,mini:s.getElementById('pcHealthMini').textContent,page:s.getElementById('pcHealthPage').textContent,signal:s.getElementById('pcxVaultSignal').dataset.visible,vaultUrgent:s.getElementById('pcHealthVault').dataset.urgent,pinText:pin.textContent.replace(/\s+/g,' ').trim(),pinDisplay:getComputedStyle(pin).display,pinSetting:h.dataset.pcxStatusPin,mainState:h.dataset.pcxMainState,alert:v.getElementById('pcVaultAlert').dataset.active,strictness:v.getElementById('pcxVaultStrictness').value,note:v.getElementById('pcxVaultPolicyNote').textContent};}''')
    assert balanced['title']=='Chat complete' and balanced['page']=='current' and balanced['signal']=='0' and balanced['vaultUrgent']=='0', balanced
    assert balanced['pinSetting']=='1' and balanced['pinDisplay']=='flex' and 'Active 2' in balanced['pinText'] and 'Stale 1' in balanced['pinText'] and 'Done 4' in balanced['pinText'], balanced
    assert balanced['mainState']=='completed' and balanced['alert']=='0' and balanced['strictness']=='balanced' and 'suppressed' in balanced['note'].lower(), balanced
    page.evaluate("document.getElementById('projectConstellationOutputVault').shadowRoot.getElementById('pcxVaultStrictness').value='strict';document.getElementById('projectConstellationOutputVault').shadowRoot.getElementById('pcxVaultStrictness').dispatchEvent(new Event('change',{bubbles:true}));")
    page.wait_for_timeout(250)
    strict=page.evaluate('''() => {const s=document.getElementById('projectConstellationHealthHud').shadowRoot;const v=document.getElementById('projectConstellationOutputVault').shadowRoot;return {signal:s.getElementById('pcxVaultSignal').dataset.visible,signalText:s.getElementById('pcxVaultSignal').textContent,page:s.getElementById('pcHealthPage').textContent,alert:v.getElementById('pcVaultAlert').dataset.active,alertTitle:v.getElementById('pcVaultAlertTitle').textContent,stored:window.__settings.outputWarningStrictness};}''')
    assert strict['signal']=='1' and '1 difference' in strict['signalText'] and strict['page']=='vault check', strict
    assert strict['alert']=='1' and strict['alertTitle']=='Saved/page mismatch detected' and strict['stored']=='strict', strict
    page.evaluate("document.getElementById('projectConstellationHealthHud').shadowRoot.getElementById('pcxChatPin').click()")
    page.wait_for_timeout(60);assert page.evaluate('window.__opened.length')==1
    shot=pathlib.Path(os.environ.get('PROJECT_CONSTELLATION_HEALTH_SCREENSHOT',str(root/'dist/pulse-ux-smoke.png')));shot.parent.mkdir(parents=True,exist_ok=True);page.screenshot(path=str(shot),full_page=False)
    print(json.dumps({'balanced':balanced,'strict':strict,'errors':errors},sort_keys=True));assert not errors;browser.close()